Token=90091783810873919:0:gTJ5QJzLZuvx8VkXLFd24gy2rcKLjq
URI=wss://d1.nandbox.net:5020/nandbox/api/
DownloadServer=https://d1.nandbox.net:5020/nandbox/download/
UploadServer=https://d1.nandbox.net:5020/nandbox/upload/